### ISSUE TITLE
是否支持gatewayswagger

### ISSUE THREAD

**Issue by gemingzhe** [iSoftStoneGroup/EazyBuilder#17]

**Comment by qiujin001** [comment]
支持swaager,eazybuilder-server\pipeline\jenkins-client\pom.xml中已经包含了swaager的相关依赖：
		<dependency>
			<groupId>com.mangofactory</groupId>
			<artifactId>swagger-springmvc</artifactId>
			<version>1.0.2</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-web</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-webmvc</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

可以在eazybuilder-server\pipeline\jenkins-client\config中的yaml配置文件，增加swaager相关配置，例如：


nacos:
  ip: ${NACOS_IP:nacos.xxxx.cn}
  port: ${NACOS_PORT:80}
  username: ${NACOS_USER:xxx}
  password: ${NACOS_PASSWORD:xxx}
spring:
  application:
    name: jenkins-client
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      config:
        enabled: true
        namespace: ${NACOS_SPACE:local}
        group: DEFAULT_GROUP
        server-addr: ${nacos.ip}:${nacos.port}
        file-extension: yml
        # 公用的配置文佳，如：redis,kafka的配置
        shared-configs:
          - data-id: rabbitmq.yml
            group: DEFAULT_GROUP
            refresh: true
          - data-id: redis-common.yml
            group: DEFAULT_GROUP
            refresh: true
          - data-id: cache.yml
            group: DEFAULT_GROUP
            refresh: true
      discovery:
        namespace: ${NACOS_SPACE:local}
        enabled: true
        server-addr: ${nacos.ip}:${nacos.port}
        metadata:
          swagger: http://${LOCAL_IP:${spring.cloud.client.ip-address}}:${server.port:}/swagger-resources
          service.name: 持续集成-nacos
