### ISSUE TITLE
a issue

### ISSUE THREAD

**Issue by aiJiangM** [iSoftStoneGroup/EazyBuilder#21]
我对你们的这个项目很感兴趣，请问文档能详细些吗？可否有样板的demo查看，或者一些功能的截图

**Comment by iSoftStoneGroup** [comment]
系统功能截图请参照，下面的url：
https://github.com/iSoftStoneGroup/EazyBuilder/wiki/系统主要功能截图
如有问题，可以扫码加入微群来进行沟通。

**Comment by iSoftStoneGroup** [comment]
已解决
