### ISSUE TITLE
查询条件缓存不对

### ISSUE THREAD

**Issue by flyfastone** [iSoftStoneGroup/EazyBuilder#27]
在流水线执行页面查询后，再进入流水线日志页面查看，没有输入查询条件，但是把上一步的条件带进来了，而且没有办法清除
![image](https://user-images.githubusercontent.com/110451882/183621787-6abd41cc-2470-44ba-bfb8-c0141f9985a8.png)

![image](https://user-images.githubusercontent.com/110451882/183621906-c89ff3a4-c191-437c-8402-f3f6b77a977b.png)

**Comment by iSoftStoneGroup** [comment]
已修复
