### ISSUE TITLE
执行流水线时后报错404

### ISSUE THREAD

**Issue by sohostysummer** [iSoftStoneGroup/EazyBuilder#34]
1.可以创建job，但是run的时候就报错
<img width="824" alt="1662621681560_B74D7CC6-FB53-472f-A5EB-EE3C577465BF" src="https://user-images.githubusercontent.com/111331271/189252784-213c6ecf-9d8d-464b-857b-fba177ec0bee.png">

**Comment by 1yangkun12131111** [comment]
这种情况一般是由于修改jenkins的域名/ip影响的。
如果有修改过jenkins地址的话，请按以下步骤排查：
执行单测TestJenkinsClient 
![image](https://user-images.githubusercontent.com/109200388/189254754-2cca4cdd-d1e7-4551-956a-af260f47c2fe.png)
![image](https://user-images.githubusercontent.com/109200388/189254926-464648ce-676e-48f1-bdbd-7a3734dad415.png)
![image](https://user-images.githubusercontent.com/109200388/189255092-0c060e78-773b-4f09-a1e9-6e8488ccb4b2.png)
![image](https://user-images.githubusercontent.com/109200388/189255235-7b40c426-c003-43d2-b902-73c6f4c776ad.png)

**Comment by sohostysummer** [comment]
好的，我试试看，谢谢

**Comment by iSoftStoneGroup** [comment]
已解决
