### ISSUE TITLE
前端页面-历史构建记录中sonarqube链接有问题

### ISSUE THREAD

**Issue by 1yangkun12131111** [iSoftStoneGroup/EazyBuilder#45]
问题原因：项目跑起来后，我发现历史构建记录中有一个小的页签，会展示sonarqube扫描的一些代码质量，但是我点击了超链接后确发现链接不对。
修复方式：sonarqube的链接居然是写死的，而且是在前端的js中写死的，这个需要改成动态加载的。
<img width="716" alt="1665222826779" src="https://user-images.githubusercontent.com/109200388/194701628-6da22726-36f5-42e4-ad8e-dd17f5a06662.png">
<img width="755" alt="微信图片_20221008175100" src="https://user-images.githubusercontent.com/109200388/194701533-62e9d879-1feb-4b37-b9a4-8e2948d675bc.png">

**Comment by Bit-McDull** [comment]
您好，感谢反馈，我们已经定位到问题，会在下一个版本中进行修复。希望能够继续得到您的反馈与支持，欢迎您向我们提出新的建议。
<img width="551" alt="1" src="https://user-images.githubusercontent.com/109252081/194735287-b793cac7-d5d8-407a-8f56-6ae7372ac48d.png">

**Comment by iSoftStoneGroup** [comment]
已修复
